### ISSUE TITLE
Main Pages # 1

### ISSUE THREAD

**Issue by olsi10** [olsi10/StudentMemories#13]
![image](https://user-images.githubusercontent.com/87300199/172174655-61474f06-6efd-4072-bc6b-33e6b6e9c186.png)

## position : fixed:

![image](https://user-images.githubusercontent.com/87300199/172174809-5fb86890-0650-41ce-a280-4de6f0db8722.png)

## 추후 JS 코드로 햄버거 메뉴로 변경할 것인가??

예를 들어, 크기를 위에 사진처럼 줄였을 때
첫번째 사진 헤더에 햄버거 메뉴로 변하고  position : fixed?

아리까리합니다!~

**Comment by 55soup** [comment]
내릴때 어떻게 불편한가요? 궁금합니다.


추후 JS코드로 줄였을 때 메뉴들이 햄버거 메뉴로 바뀌고
눌렀을 때 2번째 사진처럼 나오게 하려고합니다.!
![image](https://user-images.githubusercontent.com/86298664/172176341-cd97f8e0-0ced-430d-9ba9-f46a67fc401c.png)
엉성하지만 요런식으로 ^^

**Comment by olsi10** [comment]
불편함 해결!! 첨부 사진이 제가 원하는 구현 모습이었습니다. 감사해요~

**Comment by 55soup** [comment]
넵 ~
