### ISSUE TITLE
모바일 - 햄버거메뉴 아이콘 트랜지션

### ISSUE THREAD

**Issue by 55soup** [olsi10/StudentMemories#19]
![image](https://user-images.githubusercontent.com/86298664/173407065-4880e029-0a14-4c0f-851f-a68a7c4bb85b.png)
+ 햄버거메뉴 아이콘 눌렀을 때 "x"버튼으로 toggle
+ 자연스러운 애니메이션

**Comment by olsi10** [comment]
![image](https://user-images.githubusercontent.com/87300199/175970590-1172db05-8b21-451e-a0c3-f78d2099eb8f.png)

선주의 활약으로 완료!
