### ISSUE TITLE
album페이지

### ISSUE THREAD

**Issue by 55soup** [olsi10/StudentMemories#7]
album페이지 wrap으로 지정하면 홀수로 남았을 때 자꾸 이렇게 됨ㅠ
![image](https://user-images.githubusercontent.com/86298664/172159655-45809678-9930-4973-8a3e-75a1de1eebcd.png)

피그마처럼 이렇게 됐음 좋겠음
![image](https://user-images.githubusercontent.com/86298664/172159737-7e1e039d-9742-4c98-bb6d-edd4e2c5931a.png)

**Comment by olsi10** [comment]
개발자 입장에서는 첫 번째 사진이 편하지만
사용자가 봤을 때에는 익숙하고 편리한 게 두 번째니까 최대한 해결해봅세!!
